<?xml version="1.0" encoding="utf-8"?><Database Name="coffee" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-SDV5GRR\SQLEXPRESS;Initial Catalog=coffee;Persist Security Info=True;User ID=sa" SettingsObjectName="project.Properties.Settings" SettingsPropertyName="coffeeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.admin" Member="admins">
    <Type Name="admin">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.product" Member="products">
    <Type Name="product">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="cat_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="create_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="product_order_detail" Member="order_details" ThisKey="id" OtherKey="pro_id" Type="order_detail" />
      <Association Name="category_product" Member="category" ThisKey="cat_id" OtherKey="id" Type="category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.category" Member="categories">
    <Type Name="category">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="mausac" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="category_product" Member="products" ThisKey="id" OtherKey="cat_id" Type="product" />
    </Type>
  </Table>
  <Table Name="dbo.[order]" Member="orders">
    <Type Name="order">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="cus_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="table_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="emp_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="create_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="total_price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="order_order_detail" Member="order_details" ThisKey="id" OtherKey="order_id" Type="order_detail" />
      <Association Name="employee_order" Member="employee" ThisKey="emp_id" OtherKey="id" Type="employee" IsForeignKey="true" />
      <Association Name="customer_order" Member="customer" ThisKey="cus_id" OtherKey="id" Type="customer" IsForeignKey="true" />
      <Association Name="coffee_table_order" Member="coffee_table" ThisKey="table_id" OtherKey="id" Type="coffee_table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.order_details" Member="order_details">
    <Type Name="order_detail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="order_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pro_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="order_order_detail" Member="order" ThisKey="order_id" OtherKey="id" Type="order" IsForeignKey="true" />
      <Association Name="product_order_detail" Member="product" ThisKey="pro_id" OtherKey="id" Type="product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.employee" Member="employees">
    <Type Name="employee">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="card" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="employee_order" Member="orders" ThisKey="id" OtherKey="emp_id" Type="order" />
    </Type>
  </Table>
  <Table Name="dbo.customer" Member="customers">
    <Type Name="customer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="create_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="customer_order" Member="orders" ThisKey="id" OtherKey="cus_id" Type="order" />
      <Association Name="customer_booking" Member="bookings" ThisKey="id" OtherKey="cus_id" Type="booking" />
    </Type>
  </Table>
  <Table Name="dbo.coffee_table" Member="coffee_tables">
    <Type Name="coffee_table">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="coffee_table_order" Member="orders" ThisKey="id" OtherKey="table_id" Type="order" />
      <Association Name="coffee_table_booking" Member="bookings" ThisKey="id" OtherKey="table_id" Type="booking" />
    </Type>
  </Table>
  <Table Name="dbo.booking" Member="bookings">
    <Type Name="booking">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="start_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="table_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cus_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="end_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="customer_booking" Member="customer" ThisKey="cus_id" OtherKey="id" Type="customer" IsForeignKey="true" />
      <Association Name="coffee_table_booking" Member="coffee_table" ThisKey="table_id" OtherKey="id" Type="coffee_table" IsForeignKey="true" />
    </Type>
  </Table>
</Database>